# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_dom', models.CharField(max_length=20, verbose_name='Код дома')),
                ('number', models.IntegerField(max_length=5, verbose_name='Номер дома')),
                ('index', models.CharField(max_length=1, verbose_name='Индекс дома')),
                ('korp', models.IntegerField(max_length=5, verbose_name='Корпус дома')),
                ('prim', models.TextField(verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Lics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lics', models.CharField(max_length=11, verbose_name='Лицевой счет')),
                ('kod_dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dom')),
            ],
        ),
        migrations.CreateModel(
            name='Nas_punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.AddField(
            model_name='dom',
            name='nas_punkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Nas_punkt'),
        ),
        migrations.AddField(
            model_name='dom',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Street'),
        ),
    ]
