# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='korp',
            field=models.IntegerField(verbose_name='Корпус дома'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='number',
            field=models.IntegerField(verbose_name='Номер дома'),
        ),
    ]
