# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170419_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvartiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('kol_komnat', models.IntegerField(blank=True, verbose_name='Количество комнат')),
            ],
        ),
        migrations.RemoveField(
            model_name='dom',
            name='kod_dom',
        ),
        migrations.RemoveField(
            model_name='lics',
            name='id',
        ),
        migrations.AlterField(
            model_name='dom',
            name='index',
            field=models.CharField(blank=True, max_length=1, verbose_name='Индекс дома'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='prim',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='lics',
            name='lics',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='kvartiry',
            name='kod_dom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dom'),
        ),
    ]
