# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170419_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvartiry',
            name='kol_komnat',
        ),
    ]
