# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170419_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dom',
            options={'verbose_name': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='kvartiry',
            options={'verbose_name': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='lgoty',
            options={'verbose_name': 'Льготы'},
        ),
        migrations.AlterModelOptions(
            name='lics',
            options={'verbose_name': 'Лицевые счета'},
        ),
        migrations.AlterModelOptions(
            name='nas_punkt',
            options={'verbose_name': 'Населенные пункты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физические лица'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улицы'},
        ),
        migrations.AlterModelOptions(
            name='tip_lgoty',
            options={'verbose_name': 'Типы льгот'},
        ),
        migrations.AlterField(
            model_name='person',
            name='dateOfDeath',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
